local limitedRefIds = {}
limitedRefIds["corprus_stalker_fyr03"] = 1
limitedRefIds["daren adryn"] = 1
limitedRefIds["corprus_stalker_fyr02"] = 1
limitedRefIds["dovor oren"] = 1
limitedRefIds["graring"] = 1
limitedRefIds["dagoth draven"] = 1
limitedRefIds["golena sadri"] = 1
limitedRefIds["dreamer_talker02"] = 1
limitedRefIds["ethys savil"] = 1
limitedRefIds["dagoth fovon"] = 1
limitedRefIds["geon auline"] = 1
limitedRefIds["alfe fyr"] = 1
limitedRefIds["mirisa"] = 1
limitedRefIds["sovor trandel"] = 1
limitedRefIds["divayth fyr"] = 1
limitedRefIds["ahnia"] = 1
limitedRefIds["aldam berendus"] = 1
limitedRefIds["falco galenus"] = 1
limitedRefIds["vadusa sathryon"] = 1
limitedRefIds["kaushad"] = 1
limitedRefIds["yngling half-troll"] = 1
limitedRefIds["sul-matuul"] = 1
limitedRefIds["falx carius2"] = 1
limitedRefIds["mossanon"] = 1
limitedRefIds["corprus_lame_fyr03"] = 1
limitedRefIds["erich the unworthy"] = 1
limitedRefIds["thervam drelas"] = 1
limitedRefIds["hroldar the strange"] = 1
limitedRefIds["han-ammu"] = 1
limitedRefIds["soscean"] = 1
limitedRefIds["bolvyn venim"] = 1
limitedRefIds["elanande"] = 1
limitedRefIds["arnsa thendas"] = 1
limitedRefIds["brara morvayn"] = 1
limitedRefIds["erna the quiet"] = 1
limitedRefIds["volmyni dral"] = 1
limitedRefIds["uupse fyr"] = 1
limitedRefIds["teres arothan"] = 1
limitedRefIds["baslod"] = 1
limitedRefIds["tirer belvayn"] = 1
limitedRefIds["urven davor"] = 1
limitedRefIds["tymvaul"] = 1
limitedRefIds["favel gobor"] = 1
limitedRefIds["seler favelnim"] = 1
limitedRefIds["elbert nermarc"] = 1
limitedRefIds["mathyn bemis"] = 1
limitedRefIds["felvan ienith"] = 1
limitedRefIds["zallay subaddamael"] = 1
limitedRefIds["athelyn malas"] = 1
limitedRefIds["shunari eye-fly"] = 1
limitedRefIds["dram bero"] = 1
limitedRefIds["gamin girith"] = 1
limitedRefIds["bels uvenim"] = 1
limitedRefIds["hlaren ramoran"] = 1
limitedRefIds["corprus_stalker_fyr01"] = 1
limitedRefIds["suldreni salandas"] = 1
limitedRefIds["velanda omani"] = 1
limitedRefIds["daynila valas"] = 1
limitedRefIds["corprus_lame_fyr04"] = 1
limitedRefIds["okur"] = 1
limitedRefIds["orvas dren druglord"] = 1
limitedRefIds["sinnammu mirpal"] = 1
limitedRefIds["ralos othrenim"] = 1
limitedRefIds["garisa llethri"] = 1
limitedRefIds["thanelen velas"] = 1
limitedRefIds["marasa aren"] = 1
limitedRefIds["madrale thirith"] = 1
limitedRefIds["ordinator_mh_tbasement"] = 1
limitedRefIds["yagrum bagarn"] = 1
limitedRefIds["marcel maurard"] = 1
limitedRefIds["corprus_lame_fyr02"] = 1
limitedRefIds["arvama rathri"] = 1
limitedRefIds["calvario"] = 1
limitedRefIds["brandr"] = 1
limitedRefIds["beyte fyr"] = 1
limitedRefIds["larisus dergius"] = 1
limitedRefIds["uryn maren"] = 1
limitedRefIds["thelsa dral"] = 1
limitedRefIds["fjol"] = 1
limitedRefIds["drarayne thelas"] = 1
limitedRefIds["corprus_stalker_fgcs"] = 1
limitedRefIds["ienas sarandas"] = 1
limitedRefIds["sevilo othan"] = 1
limitedRefIds["nevena ules"] = 1
limitedRefIds["rat_telvanni_unique_2"] = 2
limitedRefIds["athyn sarethi"] = 1
limitedRefIds["vistha_kai"] = 1
limitedRefIds["uleni heleran"] = 1
limitedRefIds["corprus_lame_fyr01"] = 1
limitedRefIds["dreamer prophet"] = 1
limitedRefIds["carnius magius"] = 1
limitedRefIds["delte fyr"] = 1
limitedRefIds["olvyne dobar"] = 1
limitedRefIds["crassius curio"] = 1
limitedRefIds["smokey morth"] = 1
limitedRefIds["j'dhannar"] = 1
limitedRefIds["cunius pelelius"] = 1
limitedRefIds["dudley"] = 1
limitedRefIds["dagoth_hlevul"] = 1
limitedRefIds["miner arobar"] = 1
limitedRefIds["dreamer_02"] = 1
limitedRefIds["hanarai assutlanipal"] = 1
limitedRefIds["vivec_god"] = 1
limitedRefIds["hlireni indavel"] = 1
limitedRefIds["hroldar the strange_b"] = 1
limitedRefIds["dralora favelnim"] = 1

return limitedRefIds
